### ISSUE TITLE
missing documentation for DeepTDA

### ISSUE THREAD

**Issue by luigibonati** [luigibonati/mlcvs#16]
@EnricoTrizio

**Comment by luigibonati** [comment]
actually, I think it is better to first reorganize the code (e.g. dividing into different submodules : supervised- unsupervised-slow cvs ) and then write the documentation

**Comment by thangckt** [comment]
`mkdocs + mkdocstring` provides a convenient way to extract documentation from python function automatically.
This may mitigate your work

**Comment by luigibonati** [comment]
Closed since it has been fixed in the lightning branch
